#In this notebook we are going to cover some of the most fundamental concepts of tensors using TensorFlow.

In [6]:
## Introduction to Tensors

%pip install tensorflow
import tensorflow as tf
print(tf.__version__)

Note: you may need to restart the kernel to use updated packages.
2.19.0


In [7]:
## Creating Tensors with tf.constant

scalar= tf.constant(8)
scalar


<tf.Tensor: shape=(), dtype=int32, numpy=8>

In [8]:
## check number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [9]:
## create a vector

vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [10]:
## check the dimension of our vector 
vector.ndim

1

In [11]:
## Create a matrix (has more than 1 dimension)
matrix= tf.constant([[10,7],
                    [7,10]])

matrix



<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [12]:
## Create a matrix (has more than 1 dimension)
matrix= tf.constant([[100,7],
                    [7,10]])

matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,   7],
       [  7,  10]], dtype=int32)>

In [13]:
## create another matrix
another_matrix = tf.constant ([[10., 7.],
                              [3., 2.],
                              [8., 9.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [14]:
##whats the number of dimensions of another matrix
another_matrix.ndim

2

In [16]:
## lets create a tesnsor
tensor = tf.constant([[[1,2,3],
                       [4,5,6]],
                       [[7,8,9],
                       [10,11,12]],
                          [[13,14,15],
                          [16,17,18]]])

tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [17]:
tensor.ndim

3

In [22]:
## create the same tensor with tf.Variable
changeable_tensor = tf.Variable([10,7])
unchangeable_tensor = tf.constant([10,7])

changeable_tensor     
unchangeable_tensor

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>