In [2]:
import tensorflow as tf

##creating random tensors
Random tensors are tensors of some arbitary size which contain random numbers.

In [3]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3, 2))
random_1
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3, 2))
random_2

random_1==random_2

<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

In [6]:
##shuffle the order of the order of elementsin the tensor

not_shuffled = tf.constant ([[10,7],
                             [3,5],
                             [2,4]])
not_shuffled.ndim

2

In [7]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  5],
       [ 2,  4]], dtype=int32)>

In [12]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 2,  4],
       [10,  7],
       [ 3,  5]], dtype=int32)>

In [17]:
tf.random.set_seed(42)
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  5],
       [ 2,  4]], dtype=int32)>